### ISSUE TITLE
JwtTokenAuthenticationFilter invoked for every uri even though permitAll

### ISSUE THREAD

**Issue by upen4a3** [hantsy/spring-reactive-jwt-sample#57]
Hi hansty,

Thanks for the great example.I am facing an issue where Filter is called for every URI even for /actuator/health.Is that expected behavior ?How can we exclude /actuator/**?

**Comment by hantsy** [comment]
Exclude the uri in the Spring Security config, please.

Add your path to this line, https://github.com/hantsy/spring-reactive-jwt-sample/blob/master/src/main/java/com/example/demo/config/SecurityConfig.java#L37

**Comment by upen4a3** [comment]
I don't think that works.i added  **/actuator/**** to that line https://github.com/hantsy/spring-reactive-jwt-sample/blob/master/src/main/java/com/example/demo/config/SecurityConfig.java#L37 ,but the filter is still invoked.

**Comment by hantsy** [comment]
File an issue on spring boot.
